# Generated by Django 4.2.4 on 2023-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employe_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='pincode',
        ),
        migrations.AddField(
            model_name='employe',
            name='password',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
